### ISSUE TITLE
go back to stable swift3 pods

### ISSUE THREAD

**Issue by funkenstrahlen** [funkenstrahlen/xenim-ios-app#173]

**Comment by B-Lach** [comment]
I'm working atm at this. 
Is it ok to change the Deployment Target to iOS 10 or do you want to stay on 9.3 to support older devices?

**Comment by funkenstrahlen** [comment]
I am already 80% through this process. I appreciate your help. I think we should communicate first to work together effectively.

I will post more details here later today or tomorrow.

**Comment by B-Lach** [comment]
Sure, no problem.

**Comment by funkenstrahlen** [comment]
I just pushed my version3 feature branch to github. There is a lot of unfinished progress in there:

* migration to ios10 notifications registration (finished but untested)
* widget support (unfinished)
* swift3 migration (unfinished, still seeing a lot of compile errors)
* removal of kdeAudioPlayer pod and migration to ios10 AVPlayer code (unfinished)
* preparation TLS API
* praparation for high resolution coverarts

I also have started to work on a separate app which is independent from a specific streaming network like Xenim. I would love to support Xenim and Studiolink streaming with the new app. Currently I do not spend a lot of time on this Xenim app as I want to see how many podcaster will keep using Xenim if the new Studiolink streaming button makes its way into Ultraschall at the end of the year.

I would love to get in closer contact to coordinate. Can you please send me an email? https://funkenstrahlen.de/contact/
