### ISSUE TITLE
playback does not start from lockscreen

### ISSUE THREAD

**Issue by funkenstrahlen** [funkenstrahlen/xenim-ios-app#44]
- play a stream
- lock phone
- pause stream
- wait some time
- try to play again
- nothing happens

**Comment by funkenstrahlen** [comment]
test new develop release

**Comment by funkenstrahlen** [comment]
this might be fixed with iOS 10 AVPlayer fixes

**Comment by B-Lach** [comment]
Do you have any new information?
I found your rdar yesterday and replaced the url in the gist with an .m3u file and it's working.
I haven't looked if it's working from the look screen as well but probably it does.
